#!/bin/bash

# *******************************{begin:header}******************************
#                  spssio - http://code.google.com/p/spssio/                 
# ***************************************************************************
# 
#       Java classes for reading and writing 
#       SPSS/PSPP Portable and System files
# 
#       Copyright (C) 2013 Jani Hautamaki <jani.hautamaki@hotmail.com>
# 
#       Licensed under the terms of GNU General Public License v3.
# 
#       You should have received a copy of the GNU General Public License v3
#       along with this program as the file LICENSE.txt; if not, please see
#       http://www.gnu.org/licenses/gpl-3.0.html
# 
# ********************************{end:header}*******************************

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
java -cp ${MYDIR}/../build.dir/classes.jar: spssio.util.NumberSystemTool $@

